import { callClaude } from './anthropic'
import { CATS } from '../data/categories'

const EXCLUDED = ['id', 'cat', 'subcat', 'ownerName', 'ownerColor', 'ownerEmail',
  'createdAt', 'status', 'reviewCount', 'avgRating']

export async function generateContract(listing, userName, userRole) {
  const subLabel = CATS[listing.cat]?.sub?.[listing.subcat]?.label || listing.cat
  const isSeeker   = userRole === 'seeker'
  const providerName = isSeeker ? listing.ownerName : userName
  const seekerName   = isSeeker ? userName : listing.ownerName

  const details = Object.entries(listing)
    .filter(([k]) => !EXCLUDED.includes(k))
    .map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`)
    .join('\n')

  const prompt =
    `Generate a complete professional contract for this ClearSign marketplace listing.\n` +
    `Listing type: ${subLabel}\n` +
    `Title: ${listing.title}\n` +
    `Location: ${listing.location}\n` +
    `${details}\n` +
    `Description: ${listing.description || ''}\n` +
    `Provider: ${providerName}\n` +
    `Seeker: ${seekerName}\n` +
    `Write a full contract with UPPERCASE section headers, numbered clauses, ` +
    `protective terms for both parties, and signature blocks. Output ONLY the contract text.`

  try {
    const text = await callClaude({ messages: [{ role: 'user', content: prompt }], max_tokens: 1000 })
    return text || basicContract(listing, providerName, seekerName)
  } catch {
    return basicContract(listing, providerName, seekerName)
  }
}

function basicContract(listing, providerName, seekerName) {
  const subLabel = CATS[listing.cat]?.sub?.[listing.subcat]?.label || listing.cat
  const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  const details = Object.entries(listing)
    .filter(([k]) => !EXCLUDED.includes(k))
    .map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`)
    .join('\n')

  return `${subLabel.toUpperCase()} AGREEMENT

Date: ${today}

PARTIES
Provider: ${providerName}
Seeker: ${seekerName}
Location: ${listing.location}

LISTING DETAILS
${details}

TERMS
Both parties agree to the terms above. This agreement is binding from the date signed.

DISCLAIMER
AI-generated by ClearSign. Consult an attorney for complex situations.

PROVIDER SIGNATURE
${providerName}: _________________________ Date: [DATE SIGNED]

SEEKER SIGNATURE
${seekerName}: _________________________ Date: [DATE SIGNED]`
}
